# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[staging]
[staging.global.parameters]
stack_name = "sc-platform-pii-lambda-staging"

[staging.build.parameters]
cached = true
parallel = true

[staging.validate.parameters]
lint = true

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[staging.package.parameters]
resolve_s3 = true

[staging.sync.parameters]
watch = true

[staging.local_start_api.parameters]
warm_containers = "EAGER"

[staging.local_start_lambda.parameters]
warm_containers = "EAGER"



[production]
[production.global.parameters]
stack_name = "sc-platform-pii-lambda-production"

[production.build.parameters]
cached = true
parallel = true

[production.validate.parameters]
lint = true

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[production.package.parameters]
resolve_s3 = true

[production.sync.parameters]
watch = true

[production.local_start_api.parameters]
warm_containers = "EAGER"

[production.local_start_lambda.parameters]
warm_containers = "EAGER"