AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sc-platform-pii-lambda

  Sample SAM Template for sc-platform-pii-lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Policies:
      - Statement:
        - Sid: FetchSecret
          Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          Resource: 'arn:aws:secretsmanager:ap-south-1:736414281642:secret:staging-platform-pii-lambda-p801Bd'
      Architectures:
        - x86_64